spring:
  flyway:
   enabled: true
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: essiakpevwe
    password: 123@Zuckerberg@12
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 1 hour in milliseconds
    refreshTokenExpiration: 604800


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

